#include <AVUICommon.h>
#include <AVUISplineKeyFrames.h>

REGISTER_ELEMENT_BEGIN(AVUI::SplineSingleKeyFrame)

    REGISTER_DEFAULT_FACTORY()
    REGISTER_PROPERTY(KeySpline)
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::SplineDoubleKeyFrame)

    REGISTER_DEFAULT_FACTORY()
    REGISTER_PROPERTY(KeySpline)
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::SplinePointKeyFrame)

    REGISTER_DEFAULT_FACTORY()
    REGISTER_PROPERTY(KeySpline)
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::SplineColorKeyFrame)

    REGISTER_DEFAULT_FACTORY()
    REGISTER_PROPERTY(KeySpline)
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::SplineVector3DKeyFrame)

    REGISTER_DEFAULT_FACTORY()
    REGISTER_PROPERTY(KeySpline)
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::SplinePoint3DKeyFrame)

    REGISTER_DEFAULT_FACTORY()
    REGISTER_PROPERTY(KeySpline)
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::SplineRotation3DKeyFrame)

    REGISTER_DEFAULT_FACTORY()
    REGISTER_PROPERTY(KeySpline)
REGISTER_ELEMENT_END()


namespace AVUI {


}; // namespace AVUI
