#include <AVUICommon.h>
#include <AVUILinearKeyFrames.h>

REGISTER_ELEMENT_BEGIN(AVUI::LinearSingleKeyFrame)

    REGISTER_DEFAULT_FACTORY()
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::LinearDoubleKeyFrame)

    REGISTER_DEFAULT_FACTORY()
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::LinearPointKeyFrame)

    REGISTER_DEFAULT_FACTORY()
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::LinearColorKeyFrame)

    REGISTER_DEFAULT_FACTORY()
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::LinearVector3DKeyFrame)

    REGISTER_DEFAULT_FACTORY()
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::LinearPoint3DKeyFrame)

    REGISTER_DEFAULT_FACTORY()
REGISTER_ELEMENT_END()

REGISTER_ELEMENT_BEGIN(AVUI::LinearRotation3DKeyFrame)

    REGISTER_DEFAULT_FACTORY()
REGISTER_ELEMENT_END()


namespace AVUI {


}; // namespace AVUI
